### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by rubenkuipers** [heldr/gulp-smushit#1]
Hi,

I exactly used your example gulp task from the readme, but I only get this error:

```
SyntaxError: Unexpected token <
at Object.parse (native)
at EventEmitter.ImageFile (/Users/rubenkuipers/www/test/concrete5test/application/themes/diefac/node_modules/gulp-smushit/node_modules/smosh/lib/ImageFile.js:11:25)

at EventEmitter.onOptimize (/Users/rubenkuipers/www/test/concrete5test/application/themes/diefac/node_modules/gulp-smushit/node_modules/smosh/index.js:36:25)
at EventEmitter.emit (events.js:107:17)
at EventEmitter.onEnd (/Users/rubenkuipers/www/test/concrete5test/application/themes/diefac/node_modules/gulp-smushit/node_modules/smosh/lib/WebService.js:17:8)
at IncomingMessage.emit (events.js:129:20)
at _stream_readable.js:908:16
at process._tickCallback (node.js:355:11)
```

What is going wrong here?

**Comment by heldr** [comment]
Seems like Yahoo stopped maintaining Smushit webservice :cry: :cry: :cry: 

http://www.phpied.com/smush-it-is-dead-long-live-smushing/

**Comment by heldr** [comment]
So, based on the recent facts, this project will be deprecated :(
